import AppLayout from "@/components/AppLayout";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image" href="/booking-hero.svg" />
        <link rel="preload" as="image" href="/claudia-hero.svg" />
        <link rel="preload" as="image" href="/payment.svg" />
        <link rel="preload" as="image" href="/issues.svg" />
        <link rel="preload" as="image" href="/faq-hero.svg" />
        <link rel="preload" as="image" href="/payment-1.svg" />
        <link rel="preload" as="image" href="/payment-2.svg" />
      </head>

      <body className="overflow-x-hidden w-full">
        {/* <Toaster /> */}
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
