import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { Toaster } from "sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image" href="/booking-hero.svg" />
        <link rel="preload" as="image" href="/claudia-hero.svg" />
        <link rel="preload" as="image" href="/payment.svg" />
        <link rel="preload" as="image" href="/issues.svg" />
        <link rel="preload" as="image" href="/faq-hero.svg" />
        <link rel="preload" as="image" href="/payment-1.svg" />
        <link rel="preload" as="image" href="/payment-2.svg" />
      </head>

      <body className="font-avenir">
        <Toaster />
        <NavBar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
